sudo: required
services:
  - docker
language: generic
before_install:
  - docker build -t ashah2193/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ashah2193/client-test npm run test -- --coverage
after_success:
  - docker build -t ashah2193/multi-client ./client
  - docker build -t ashah2193/multi-nginx ./nginx
  - docker build -t ashah2193/multi-server ./server
  - docker build -t ashah2193/multi-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ashah2193/multi-client
  - docker push ashah2193/multi-nginx
  - docker push ashah2193/multi-server
  - docker push ashah2193/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-852550184847"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY